# Generated by Django 4.2.8 on 2025-06-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity_remain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='variety',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
