# Generated by Django 4.2.8 on 2025-06-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_category_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quantity_remain',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='total_quantity',
        ),
    ]
