# Generated by Django 4.2.8 on 2025-06-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
    ]
