# Generated by Django 4.2.8 on 2025-06-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
