# Generated by Django 4.2.8 on 2025-06-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quantity',
            new_name='stock',
        ),
    ]
