# Generated by Django 4.2.8 on 2025-06-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_rename_quantity_item_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ready for Pick Up', 'Ready for Pick Up'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
